{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "fruits-api.fullname" . }}
  labels:
    {{- include "fruits-api.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ include "fruits-api.fullname" . }}-{{ .Values.global.namespace }}.{{ .Values.global.host }}
    port:
      name: {{ .Values.gateway.port.name }}
      number: {{ .Values.gateway.port.number }}
      protocol: {{ .Values.gateway.port.protocol }}
{{- end -}}
